# Generated by Django 4.2.21 on 2025-08-17 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('idagenda', models.AutoField(db_column='idAgenda', primary_key=True, serialize=False)),
                ('fecha', models.DateField(help_text='Fecha de la agenda')),
                ('horainicio', models.TimeField(db_column='horaInicio', help_text='Hora de inicio de la agenda')),
                ('horafin', models.TimeField(db_column='horaFin', help_text='Hora de fin de la agenda')),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agendas',
                'db_table': 'agenda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('idbox', models.AutoField(db_column='idBox', primary_key=True, serialize=False)),
                ('capacidad', models.IntegerField(blank=True, help_text='Capacidad máxima del box', null=True)),
            ],
            options={
                'verbose_name': 'Box',
                'verbose_name_plural': 'Boxes',
                'db_table': 'box',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('idespecialidad', models.AutoField(db_column='idEspecialidad', primary_key=True, serialize=False)),
                ('especialidad', models.CharField(help_text='Nombre de la especialidad', max_length=100)),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'db_table': 'especialidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pasillo',
            fields=[
                ('idpasillo', models.AutoField(db_column='idPasillo', primary_key=True, serialize=False)),
                ('pasillo', models.CharField(help_text='Nombre del pasillo', max_length=100)),
            ],
            options={
                'verbose_name': 'Pasillo',
                'verbose_name_plural': 'Pasillos',
                'db_table': 'pasillo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('idprofesional', models.AutoField(db_column='idProfesional', primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre completo del profesional', max_length=100)),
            ],
            options={
                'verbose_name': 'Profesional',
                'verbose_name_plural': 'Profesionales',
                'db_table': 'profesional',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipoagenda',
            fields=[
                ('idtipoagenda', models.AutoField(db_column='idTipoAgenda', primary_key=True, serialize=False)),
                ('tipoagenda', models.CharField(db_column='tipoAgenda', help_text='Tipo de agenda (ej: Consulta, Cirugía, Urgencia)', max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de Agenda',
                'verbose_name_plural': 'Tipos de Agenda',
                'db_table': 'tipoagenda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del tipo de usuario', max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del tipo de usuario')),
                ('activo', models.BooleanField(default=True, help_text='Indica si este tipo de usuario está activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del tipo de usuario')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha de última modificación')),
            ],
            options={
                'verbose_name': 'Tipo de Usuario',
                'verbose_name_plural': 'Tipos de Usuario',
                'db_table': 'tipo_usuario',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el perfil de usuario está activo')),
                ('telefono', models.CharField(blank=True, help_text='Número de teléfono del usuario', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del perfil')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha de última modificación del perfil')),
                ('ultimo_acceso', models.DateTimeField(blank=True, help_text='Fecha y hora del último acceso del usuario', null=True)),
                ('tipo_usuario', models.ForeignKey(help_text='Tipo de usuario que define sus permisos', on_delete=django.db.models.deletion.PROTECT, to='visualizacionBoxes.tipousuario')),
                ('usuario', models.OneToOneField(help_text='Usuario de Django asociado', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
                'db_table': 'perfil_usuario',
                'ordering': ['usuario__first_name', 'usuario__last_name'],
            },
        ),
    ]
