# Generated by Django 4.2.21 on 2025-08-17 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualizacionBoxes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='pasillo_asignado',
            field=models.ForeignKey(blank=True, help_text='Pasillo asignado (solo para Personal Médico)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='visualizacionBoxes.pasillo'),
        ),
    ]
